# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-04-20 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL), max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('user', 'title')]),
        ),
    ]
